### ISSUE TITLE
proposal: is it possible to use tags to identify the latest "official" version?

### ISSUE THREAD

**Issue by sehomer** [rezeau/moodle-qtype_regexp#25]
Hi joseph,

a growing number of moodleplugins provide tags to identify the latest official releases. In some cases, the vcs tag is also shown in the moodle plugin directory, that makes updating via submodules lots easier. May I kindly ask you to also provide tags? It's always a bit tricky to find the correct commits of latest versions of plugins that do not have tagged commits.

Best regards and thanks for maintaining your plugins since years!
Sebastian

**Comment by rezeau** [comment]
Hi @sehomer ,
I have never used tags on my Moodle plugins so far, and have never been asked to do it. I think most Moodle users install my plugins from the Moodle plugins repository rather than from my github.
Anyway, if you think this can be useful I will try to understand the tag system from now on. Just one question: it would be tedious for me to add tags to all of my commits (since July 2011). Do you think it would be OK to only start now, i.e. tagging from my most recent commit dated last month?
Joseph

**Comment by sehomer** [comment]
Hi @rezeau,

thank you for the fast reply. One can add a certain tag to the commit that is equivalent to the version that is zipped in the Moodle Plugins repository. As you see in this example of the boost union theme, there are tags for the different releases / different versions:

https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/tags

Every version in the Moodle repository get's a VCS Tag Info (at the bottom of the page):
https://moodle.org/plugins/theme_boost_union/v4.5-r2/33730 

More and more developer do so.

From my point of view it would be fine (and very kind) if you just start now, to tag the commit of the release in the moodle repository in future.

Thanks for thinking about this proposal.
Best regards
Sebastian

**Comment by sehomer** [comment]
Hi Joseph, 

thank you for using your first tag, I already used it to update the qtype_regexp.

Best regards
Sebastian

**Comment by rezeau** [comment]
Glad it helped!
